# Generated by Django 3.0.3 on 2020-03-23 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_auto_20200323_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreate', models.DateTimeField(auto_now_add=True)),
                ('firstname', models.TextField(null=True)),
                ('lastname', models.TextField(null=True)),
                ('name', models.TextField(null=True)),
                ('street', models.TextField()),
                ('postal', models.TextField()),
                ('city', models.TextField()),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Order')),
            ],
        ),
    ]
