# Generated by Django 3.0.3 on 2020-03-16 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prizes', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('comment', models.TextField()),
                ('plannedValue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deadline', models.DateField()),
                ('doNext', models.TextField(choices=[('stay', 'Towar zostaje na magazynie'), ('send', 'Wysyłka dalej')])),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.Client')),
                ('prize', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prizes.Prize')),
            ],
        ),
    ]
